# Generated by Django 4.1 on 2022-08-31 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0002_alter_file_created_at_alter_file_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fileupload.folder"
            ),
        ),
    ]
