# Generated by Django 4.1 on 2022-09-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0003_alter_file_folder"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
